locale_name = "English (US)"
title = "SIMLE Technical Standard"
author = "Robert Michael Welan"
description = "Defining the blueprint for the next generation of digital storytelling. Discover the framework behind the SIMLE engine—a revolutionary standard for responsive, high-fidelity interactive books."

[cover_wordmarks]
# Localized Wordmarks (Assets specific to this language)
book_wordmark_title = "assets/images/en-us/title.webp"
book_wordmark_author = "assets/images/en-us/author.webp"
book_wordmark_description = "assets/images/en-us/description.webp"
