[project]
id = "template-placeholder-id"
version = "1.0.0"
author = "your-handle"

[structure]
# Define your language tracks. First is default.
locales = ["en-us", "zh-py"]

# The reading order of your pages
manifest = [
  "chapter01-page01.md"
]

[cover]
# Optional overrides for base-layout.css variables
# landscape = "assets/images/custom-bg-wide.webp"
# portrait = "assets/images/custom-bg-tall.webp"
